#!/usr/bin/env bash
# =============================================================================
#  setup_rocm.sh  —  AMD MI300X Environment Setup
#  Project: final_marl  (pure JAX/Flax SAC)
#
#  Run once on the server:
#    bash setup_rocm.sh
#
#  What this does:
#    1. Upgrades the 'marl' conda env to use ROCm-backed JAX
#    2. Pins all package versions to match requirements.txt
#    3. Writes ~/.bashrc_rocm with all required env vars
#    4. Adds a conda activate hook so vars load automatically
#    5. Runs a smoke test to verify GPU detection
# =============================================================================

set -euo pipefail

# ── Color helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'
log()  { echo -e "${GREEN}${BOLD}[✓]${NC} $*"; }
info() { echo -e "${CYAN}[→]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}${BOLD}[✗]${NC} $*"; exit 1; }

# ── Detect ROCm ───────────────────────────────────────────────────────────────
ROCM_PATH=/opt/rocm
[[ -d "$ROCM_PATH" ]] || err "ROCm not found at /opt/rocm. Is it installed?"
ROCM_VER=$(cat "${ROCM_PATH}/.info/version" 2>/dev/null || echo "unknown")
GPU_ARCH="gfx942"   # AMD MI300X

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║  final_marl  ·  AMD MI300X  ·  ROCm ${ROCM_VER}         ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
info "ROCm path    : ${ROCM_PATH}"
info "ROCm version : ${ROCM_VER}"
info "GPU arch     : ${GPU_ARCH} (MI300X)"
echo ""

# ── Activate conda env ────────────────────────────────────────────────────────
ENV_NAME="marl"
CONDA_BASE=$(conda info --base 2>/dev/null) || err "conda not found. Run: source ~/miniconda3/etc/profile.d/conda.sh"
source "${CONDA_BASE}/etc/profile.d/conda.sh"

if conda env list | grep -qE "^${ENV_NAME}\s"; then
    info "Activating existing conda env '${ENV_NAME}'..."
    conda activate "${ENV_NAME}"
else
    warn "Env '${ENV_NAME}' not found — creating with Python 3.10..."
    conda create -y -n "${ENV_NAME}" python=3.10
    conda activate "${ENV_NAME}"
fi
log "Python: $(python --version)  |  $(which python)"

# ── Install JAX with ROCm backend ────────────────────────────────────────────
#
#  AMD officially maintains ROCm JAX wheels here:
#    https://github.com/ROCm/jax  (tagged per ROCm + JAX version)
#
#  JAX 0.10.x / jaxlib 0.10.x are the pinned versions in requirements.txt.
#  ROCm wheels follow the format: jaxlib-JAXVER+rocmROCMVER
#
#  Strategy: install from AMD's release index with exact version pins.
#
info "Removing any existing JAX installation..."
pip uninstall -y jax jaxlib jax-rocm jaxlib-rocm 2>/dev/null || true

info "Installing JAX 0.10.2 + ROCm backend..."
# Primary: AMD's own PyPI index (updated regularly alongside ROCm releases)
pip install \
    jax==0.10.2 \
    "jaxlib==0.10.2+rocm$(echo ${ROCM_VER} | tr -d '.')" \
    --extra-index-url https://pypi.amd.com \
    --no-deps 2>/dev/null || {

    warn "AMD PyPI index failed. Trying Google's ROCm jax release index..."
    pip install "jax[rocm]" \
        -f https://storage.googleapis.com/jax-releases/rocm/jax_rocm_releases.html \
        --no-deps 2>/dev/null || {

        warn "Pinned version not found. Installing latest ROCm-compatible JAX..."
        pip install "jax[rocm]" \
            -f https://storage.googleapis.com/jax-releases/rocm/jax_rocm_releases.html
    }
}

# ── Install the rest of the JAX ecosystem ────────────────────────────────────
info "Installing Flax / Optax / Orbax..."
pip install \
    "flax==0.12.7" \
    "optax==0.2.8" \
    "orbax-checkpoint==0.11.5"

# ── Install project dependencies ──────────────────────────────────────────────
info "Installing project dependencies..."
pip install \
    "numpy==2.4.4" \
    "pandas==3.0.2" \
    "matplotlib==3.10.8" \
    "rich==13.2.0"

log "All packages installed."

# ── Verify JAX sees the GPUs ──────────────────────────────────────────────────
info "Verifying JAX GPU detection..."
python - <<'PYEOF'
import os
os.environ.setdefault("JAX_PLATFORMS", "rocm")
import jax

devices = jax.devices()
gpu_devices = [d for d in devices if d.platform == "gpu"]
print(f"  JAX version : {jax.__version__}")
print(f"  All devices : {devices}")

if gpu_devices:
    print(f"  ✓  {len(gpu_devices)} GPU device(s) detected")
else:
    print("  ⚠  No GPU devices — JAX running on CPU")
    print("     Check: HSA_OVERRIDE_GFX_VERSION, ROCR_VISIBLE_DEVICES, ROCm install")
PYEOF

# ── Write ROCm environment variables ─────────────────────────────────────────
info "Writing ~/.bashrc_rocm..."
cat > "${HOME}/.bashrc_rocm" <<ENVEOF
# ============================================================
#  ROCm / HIP environment — auto-sourced by conda activate
#  Generated by multi_agent_nav_max/setup_rocm.sh
# ============================================================

# ── ROCm paths ───────────────────────────────────────────────
export ROCM_HOME=/opt/rocm
export PATH=\${ROCM_HOME}/bin:\${ROCM_HOME}/llvm/bin:\${PATH}
export LD_LIBRARY_PATH=\${ROCM_HOME}/lib:\${ROCM_HOME}/lib64:\${LD_LIBRARY_PATH:-}

# ── GPU visibility ───────────────────────────────────────────
# Exposes all 8 MI300X GPUs.
# Override per-run with:  ROCR_VISIBLE_DEVICES=0 python train_pure_jax.py
export ROCR_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

# ── GPU architecture ─────────────────────────────────────────
# MI300X = gfx942. Change to gfx90a for MI250X.
export HSA_OVERRIDE_GFX_VERSION=${GPU_ARCH}
export PYTORCH_ROCM_ARCH=${GPU_ARCH}     # unused here but harmless

# ── JAX / XLA flags ──────────────────────────────────────────
export JAX_PLATFORMS=rocm                # force ROCm backend
export XLA_FLAGS="--xla_gpu_enable_async_all_reduce=true"

# MI300X has unified HBM — disable HBM2E-only features that cause XLA crashes
export TF_CPP_MIN_LOG_LEVEL=2           # suppress XLA info spam

# ── Replay buffer lives entirely on GPU — disable HBM fragmentation warnings ─
export HSA_ENABLE_SDMA=0                # DMA engine can conflict on MI300X

# ── JAX memory ───────────────────────────────────────────────
# Pre-allocate 90% of HBM for XLA. The 100K-buffer + 32 envs fits inside 192 GB.
export XLA_PYTHON_CLIENT_MEM_FRACTION=0.90

# ── Misc ─────────────────────────────────────────────────────
export MPLCONFIGDIR=/tmp/matplotlib_\${USER}
ENVEOF

# Append source to .bashrc if not already there
grep -q "bashrc_rocm" "${HOME}/.bashrc" 2>/dev/null \
    || echo 'source "${HOME}/.bashrc_rocm"' >> "${HOME}/.bashrc"
log "~/.bashrc_rocm written."

# ── Conda activate hook ───────────────────────────────────────────────────────
ACTIVATE_DIR="${CONDA_BASE}/envs/${ENV_NAME}/etc/conda/activate.d"
mkdir -p "${ACTIVATE_DIR}"
cat > "${ACTIVATE_DIR}/rocm_env.sh" <<'HOOKEOF'
#!/bin/bash
# Sourced automatically on `conda activate marl`
[[ -f "${HOME}/.bashrc_rocm" ]] && source "${HOME}/.bashrc_rocm"
HOOKEOF
chmod +x "${ACTIVATE_DIR}/rocm_env.sh"
log "Conda activate hook: ${ACTIVATE_DIR}/rocm_env.sh"

# ── Final smoke test ──────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━  Smoke Test  ━━━━━━━━━━━━━━━━${NC}"
python - <<'PYEOF'
import os
os.environ.setdefault("JAX_PLATFORMS", "rocm")
os.environ.setdefault("XLA_PYTHON_CLIENT_MEM_FRACTION", "0.5")

import jax
import jax.numpy as jnp
import flax.linen as nn
import optax
import time

print(f"jax     : {jax.__version__}")

# 1. Basic matmul on GPU
key = jax.random.PRNGKey(0)
x   = jax.random.normal(key, (2048, 2048))
t0  = time.time()
y   = jnp.dot(x, x).mean()
y.block_until_ready()
t1  = time.time()
print(f"[JAX]   2048×2048 matmul on {jax.devices()[0]}  →  {float(y):.4f}  ({(t1-t0)*1000:.1f}ms)")

# 2. vmap over 32 envs (mirrors train_pure_jax.py)
batch = jax.random.normal(key, (32, 5, 920))   # [E, N, obs_dim]
flat  = batch.reshape(160, 920)
W     = jax.random.normal(key, (920, 256))
out   = jnp.dot(flat, W)
out.block_until_ready()
print(f"[JAX]   vmap-style batch  (160×920 → 160×256)  ✓")

# 3. Simple Flax forward pass
class MLP(nn.Module):
    @nn.compact
    def __call__(self, x):
        x = nn.Dense(256)(x); x = nn.relu(x)
        x = nn.Dense(256)(x); x = nn.relu(x)
        return nn.Dense(2)(x)

model  = MLP()
params = model.init(key, jnp.ones((1, 920)))
out    = model.apply(params, flat)
out.block_until_ready()
print(f"[Flax]  forward pass  →  {out.shape}  ✓")

print("\n✅  All checks passed — AMD MI300X is ready for training.")
PYEOF

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║                    ✅  SETUP COMPLETE                       ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}To activate the environment:${NC}"
echo "    conda activate marl"
echo ""
echo -e "  ${BOLD}To train (single GPU — default):${NC}"
echo "    cd ~/AUV_Project/RLSim/final_marl"
echo "    ROCR_VISIBLE_DEVICES=0 python train_pure_jax.py"
echo ""
echo -e "  ${BOLD}To train on a specific GPU:${NC}"
echo "    ROCR_VISIBLE_DEVICES=2 python train_pure_jax.py"
echo ""
echo -e "  ${BOLD}To run 8 parallel sweeps (one per GPU):${NC}"
echo "    bash run_sweep.sh"
echo ""
